name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
          
jobs:
    triage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

            