name: stratergy work flow

on:
  workflow_dispatch:
      inputs:
        opened:
          description: hello
          required: true
jobs:
    self-approval-check:    
      runs-on: ubuntu-latest
      outputs:
        matrix_1: ${{ steps.set-matrix.outputs.matrix }}
      strategy:
        matrix:
          service_account: [ifd, ift, dbc]
          include:
            - service_account: 'ifd'
              project: developer 
            - service_account: 'ift'
              project: tester 
            - service_account: 'dbc'
              project: produser 
      steps:
        - id: set-matrix
          run: echo "{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
        - id: copy
          name: hello
          run: |-
            echo ${{ matrix.service_account }}
            echo ${{ matrix.project }}
    job2:
        needs: self-approval-check
        runs-on: ubuntu-latest
        steps:
          - run: |-
              echo ${{ fromJSON(needs.self-approval-check.outputs.matrix_1) }}
            