name: stratergy work flow

on:
  issues:
    types:
      - opened   
jobs:
    self-approval-check:    
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version: [10, 12, 14]
      steps:
        - id: copy
          name: hello
          run: |-
            echo ${{ matrix.version }}

            