name: stratergy work flow

on:
  workflow_dispatch:
      inputs:
        opened:
          description: hello
          required: true
jobs:
    self-approval-check:    
      runs-on: ubuntu-latest
      strategy:
        matrix:
          service_account: [ifd, ift, dbc]
          include:
            - service_account: 'ifd'
              project: developer 
            - service_account: 'ift'
              project: tester 
            - service_account: 'dbc'
              project: produser 
      steps:
        - id: copy
          name: hello
          run: |-
            echo ${{ matrix.service_account }}
            echo ${{ matrix.project }}

            