name: stratergy work flow

on:
  workflow_dispatch:
      inputs:
        opened:
          description: hello
          required: true
jobs:
    self-approval-check:    
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version: [10, 12, 14]

      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
      steps:
        - id: set-matrix
          run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
        - id: copy
          name: hello
          run: |-
            echo ${{ matrix.version }}

            